### ISSUE TITLE
Order of JSON map

### ISSUE THREAD

**Issue by abourget** [EOSIO/eosjs-json#3]
By reading https://github.com/EOSIO/eosjs-json/blob/dawn3/schema/generated.json it seems to me that the `fields` should be kept in order, contrary to the expectation that keys in a map (or a JSON object) are not guaranteed to be kept in order.

I've seen the latest eosio codebase which seems to have fixed that.. will that be applied here and throughout all the `fcbuffer` realm too ?

I'm writing Go bindings and interfaces to EOS.IO Software.. so I'd like to keep the pace with the changes :)

thanks for all the great work!

**Comment by jcalfee** [comment]
Yes it will .. right now it is on the dawn3 branch only.  Npm has libs deployed but they need a version or tag:
npm i fcbuffer@dawn3
npm i eosjs@dwan3

Those versions leave the original order for everything except a short list of of fields in eosjs..  But these versions only work with eosiod in github master (not the public testnet).  I did think of a good way to update dawn2 with this change. I can do that Monday.

**Comment by jcalfee** [comment]
fyi: I made edits to the above.. I'm done now.. promise

**Comment by jcalfee** [comment]
@abourget have you migrated to dawn3?  There is a docker folder that could be helpful, it runs the unit test using dawn3.
